<!DOCTYPE html>
<html>
<head>
    <title>JOS {{ $jos->reference_number }}</title>
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .section { margin-bottom: 15px; }
        .section-title { font-weight: bold; margin-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .total-row { font-weight: bold; }
        .no-data { color: #777; font-style: italic; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Job Order Statement</h1>
        <h2>{{ $jos->reference_number }}</h2>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <div class="section">
        <div class="section-title">Contractor Information</div>
        @if($jos->jobOrders->first() && $jos->jobOrders->first()->contractor)
            <p>Name: {{ $jos->jobOrders->first()->contractor->name }}</p>
            <p>Company: {{ $jos->jobOrders->first()->contractor->company_name }}</p>
            <p>Email: {{ $jos->jobOrders->first()->contractor->email }}</p>
            <p>Phone: {{ $jos->jobOrders->first()->contractor->phone_number }}</p>
        @else
            <p class="no-data">No contractor information available</p>
        @endif
    </div>

    <div class="section">
        <div class="section-title">Conductor Information</div>
        @if($jos->jobOrders->first() && $jos->jobOrders->first()->conductor)
            <p>Name: {{ $jos->jobOrders->first()->conductor->full_name }}</p>
            <p>Staff ID: {{ $jos->jobOrders->first()->conductor->staff_id }}</p>
            <p>Department: {{ $jos->jobOrders->first()->conductor->department_name }}</p>
            <p>Email: {{ $jos->jobOrders->first()->conductor->email ?? 'N/A' }}</p>
        @else
            <p class="no-data">No conductor information available</p>
        @endif
    </div>

    <div class="section">
        <div class="section-title">Summary</div>
        <p>Total Job Orders: {{ $jos->total_job_orders }}</p>
        <p>Total Amount: {{ number_format($jos->total_amount, 2) }}</p>
        <p>Paid Amount: {{ number_format($jos->paid_amount, 2) }}</p>
        <p>Balance Amount: {{ number_format($jos->balance_amount, 2) }}</p>
        <p>Remarks: {{ $jos->remarks ?? 'N/A' }}</p>
    </div>

    <div class="section">
        <div class="section-title">Job Order Details</div>
        @if($jos->jobOrders->count() > 0)
            <table>
                <thead>
                    <tr>
                        <th>Reference</th>
                        <th>Date</th>
                        <th>Type of Work</th>
                        <th>Actual Work</th>
                        <th>Rate</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($jos->jobOrders as $jobOrder)
                    <tr>
                        <td>{{ $jobOrder->reference_number }}</td>
                        <td> {{ \Carbon\Carbon::parse($jobOrder->date)->format('Y-m-d') }}</td>
                        <td>{{ $jobOrder->typeOfWork->name ?? 'N/A' }}</td>
                        <td>{{ $jobOrder->actual_work_completed }}</td>
                        <td>{{ number_format($jobOrder->typeOfWork->rate ?? 0, 2) }}</td>
                        <td>{{ number_format($jobOrder->amount, 2) }}</td>
                    </tr>
                    @endforeach
                    <tr class="total-row">
                        <td colspan="5" style="text-align: right;">Total:</td>
                        <td>{{ number_format($jos->total_amount, 2) }}</td>
                    </tr>
                </tbody>
            </table>
        @else
            <p class="no-data">No job orders found for this JOS</p>
        @endif
    </div>

    <div class="footer" style="margin-top: 30px;">
        <p>Generated by JOS Generation System</p>
    </div>
</body>
</html>